[package]
name = "sd-images"
version = "0.0.0"
authors = [
	"Jake Robinson <jake@spacedrive.com>",
	"Vítor Vasconcellos <vitor@spacedrive.com>",
]
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[features]
heif = ["dep:libheif-rs", "dep:libheif-sys"]

[dependencies]
image = "0.24.7"
thiserror = "1.0.48"
resvg = "0.35.0"

[target.'cfg(any(not(any(target_os = "linux", target_os = "windows")), heif_images))'.dependencies]
# both of these added *default* bindgen features in 0.22.0 and 2.0.0+1.16.2 respectively
# this broke builds as we build our own liibheif, so i disabled their default features
libheif-rs = { version = "0.22.0", default-features = false, optional = true }
libheif-sys = { version = "2.0.0+1.16.2", default-features = false, optional = true }
